# Generated by Django 4.2.4 on 2023-08-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_habilidades_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidades',
            name='hability',
        ),
        migrations.AddField(
            model_name='empleado',
            name='abilities',
            field=models.ManyToManyField(to='empleados.habilidades'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AddField(
            model_name='habilidades',
            name='ability',
            field=models.CharField(default='DEFAULT VALUE', max_length=60, verbose_name='ability'),
        ),
    ]
