# Generated by Django 4.2.4 on 2023-09-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_habilidades_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='abilities',
            field=models.ManyToManyField(blank=True, null=True, to='empleados.habilidades'),
        ),
        migrations.AlterField(
            model_name='habilidades',
            name='ability',
            field=models.CharField(default='DEFAULT VALUE', max_length=60, verbose_name='ability'),
        ),
    ]
