# Generated by Django 4.2.4 on 2023-09-01 19:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_alter_empleado_abilities_alter_habilidades_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cv',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
    ]
