# Generated by Django 4.2.4 on 2023-09-10 21:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_empleado_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cv',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Hoja de vida'),
        ),
    ]
